apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-python-cronjob
spec:
  schedule: "*/1 * * * *"  
  # suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-service
            image: vandanaa25/backup-service:latest
          restartPolicy: OnFailure
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: my-data-pvc 
          - name: google-credentials-volume
            secret:
              secretName: google-credentials


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


